package errs

// English is the language-neutral fallback: what (*Error).Error() prints and
// what Localize falls back to when a locale's catalog lacks a Code. Entries
// appear in the same order as ko.go and ja.go so the three read side by side.
var enCatalog = Catalog{
	ThisNotBound:         "'this' is not bound.",
	SuperOutsideMethod:   "Cannot use 'super' outside of a class method.",
	StaticOutsideMethod:  "Cannot use a static reference outside of a class method.",
	VariableNotFound:     "Variable '%s' not found.",
	InstantiateInterface: "'%s' is an interface, so it cannot be instantiated.",
	InstantiateAbstract:  "'%s' is an abstract class, so it cannot be instantiated.",
	StringIndexAssign:    "A string is immutable, so a character at an index cannot be reassigned.",
	NativeArgString:      "Argument %d must be a string.",
	NativeArgNumber:      "Argument %d must be a number.",
	NativeArgInteger:     "Argument %d must be a whole number.",
	NativeArgList:        "Argument %d must be a list.",
	NativeArgDict:        "Argument %d must be a dictionary.",
	NativeDictStrings:    "Argument %d must be a dictionary of strings.",
	ArgCountRange:        "Expected between %d and %d arguments.",
	JSONInvalid:          "The text is not valid JSON.",
	JSONUnsupported:      "The value contains something JSON cannot represent.",
	CSVInvalid:           "The text is not valid CSV.",
	CSVUnsupported:       "The value cannot be written as CSV. A row must be a list and a cell must be text or a number.",
	CSVDelimiter:         "The delimiter must be one character, and not a quote or a line break.",
	RegexInvalid:         "'%s' is not a valid regular expression.",
	RandomRange:          "Invalid range: the minimum %d is greater than the maximum %d.",
	RandomEmpty:          "Cannot choose from an empty list.",
	DateInvalid:          "'%s' is not a date that matches the given format.",
	NativeListNumbers:    "Argument %d must be a list of numbers.",
	NativeListStrings:    "Argument %d must be a list of strings.",
	ListNotSortable:      "Only lists of all numbers or all strings can be sorted.",
	CallbackNotBoolean:   "A function that decides a condition must return true or false.",
	ConditionNotBoolean:  "A %s value cannot be used as a condition; it must be true or false.",
	ListValueUnsupported: "Only numbers, strings, booleans and null can be compared here.",
	MathDomain:           "That value cannot be used in this calculation.",
	StatsNotEnough:       "There are not enough values to calculate this.",
	RangeStepZero:        "The step cannot be zero.",
	ResultTooLarge:       "The result would be too large.",
	TextEmptyPart:        "The text to look for cannot be empty.",
	PadFillLength:        "The fill must be exactly one character.",
	Base64Invalid:        "The text is not valid base64.",
	URLDecodeInvalid:     "The text is not valid URL encoding.",
	SleepRange:           "The time to wait must be between 0 and 3600 seconds.",
	FileNotFound:         "File or folder '%s' not found.",
	FileIsDirectory:      "'%s' is a folder, not a file.",
	FileAccessDenied:     "No permission to access '%s'.",
	FileFailed:           "Could not complete the file operation on '%s'.",
	FileBlocked:          "File access is turned off for this run.",
	NetBlocked:           "Network access is turned off for this run.",
	SocketBadHandle:      "Socket %s does not exist or is already closed.",
	SocketNotConnection:  "A listening socket cannot send or receive.",
	SocketNotListener:    "A connected socket cannot accept new connections.",
	SocketConnectFailed:  "Could not connect to '%s'.",
	SocketListenFailed:   "Could not listen on '%s'.",
	SocketTimeout:        "The operation did not finish in the time set.",
	SocketFailed:         "The socket operation could not be completed.",
	SocketPort:           "A port must be a whole number from 0 to 65535.",
	HTTPBadURL:           "'%s' is not an http or https address.",
	HTTPFailed:           "Could not send a request to '%s'.",
	HTTPTooLarge:         "The response from '%s' was too large to read completely.",
	HTTPBadMethod:        "'%s' is not a method that can be used.",
	ClassNotFound:        "Class '%s' not found.",

	GlobalFunctionNotFound: "Global function '%s' not found.",
	StaticMethodNotFound:   "Static method '%s' not found.",
	MethodNotFound:         "Method '%s' not found.",

	NotCallable:             "Not callable.",
	NotAList:                "Not a list.",
	NotIterable:             "Not iterable.",
	RangeMustBeNumbers:      "A range must be made of numbers.",
	ListIndexMustBeNumber:   "A list index must be a number.",
	SuperMemberMustBeMethod: "A parent's member can only be called as a method.",
	MethodArgMustBeNumber:   "The arguments of '%s' must be numbers.",
	MethodArgMustBeString:   "The argument of '%s' must be a string.",
	NotANumber:              "Not a number.",
	InvalidOperands:         "Invalid operands for this operator.",
	ListOnlyMethod:          "This method can only be used on a list.",

	MemberAccessOnString:    "Cannot access members on a string this way.",
	MemberAccessUnsupported: "Cannot access members on a value of type '%s'.",

	ListEmpty:             "The list is empty.",
	ListIndexOutOfRange:   "List index out of range.",
	StringIndexOutOfRange: "String index out of range.",

	DictKeyNotFound:      "Key '%v' not found.",
	StaticMemberNotFound: "Static member '%v' not found.",

	ArgCountExact:    "Expected %d argument(s).",
	TooManyArguments: "Too many arguments: expected %d, got %d.",
	MissingArgument:  "Missing argument '%s'.",

	ConstantAssignment: "Cannot reassign constant '%s'.",

	PrivateMethodAccess:   "Method '%s' is private and cannot be called from outside.",
	PrivateFieldAccess:    "Property '%s' is private and cannot be accessed from outside.",
	ProtectedMethodAccess: "Method '%s' is protected and cannot be called from outside a subclass.",
	ProtectedFieldAccess:  "Property '%s' is protected and cannot be accessed from outside a subclass.",

	InterfaceNotImplemented: "Class '%[1]s' must implement method '%[3]s' of interface '%[2]s'.",

	DivideByZero: "Division by zero.",

	ConvertToNumberFailed:     "Cannot convert '%s' to a number.",
	ConvertToNumberInvalid:    "Cannot convert this value to a number.",
	ConvertToCodeNeedsOneChar: "<%s> needs a string of length 1.",
	ConvertToTextNeedsNumber:  "Only a number can be converted to a character.",

	ImportNativeFunctionNotFound: "Native function '%[2]s' not found in DLL package '%[1]s'.",
	ImportDLLNotFound:            "DLL for package '%s' not found.",
	ImportPluginUnsupported:      "Native plugins are not supported on %s.",
	ImportManifestInvalid:        "The manifest of package '%[1]s' is not valid: %[2]s",
	ImportNativeMissing:          "Package '%[1]s' has no native library for %[2]s.",
	ImportNativeLoadFailed:       "Could not load the native library '%s'.",
	NativeCallFailed:             "Native function '%[1]s' failed: %[2]s",
	ImportUnsupportedLocale:      "Package '%[1]s' has no '%[2]s' entry point.",
	ImportPackageSyntax:          "Syntax error in file '%[2]s' of package '%[1]s'.",
	ImportPackageNotFound:        "Package '[%s]' not found.",
	ImportPackageNotInstalled:    "Package '[%s]' is not installed. 'hana install' downloads it.",
	ImportClassConflict:          "The class '%[2]s' of '%[1]s' has the same name as a class of '%[3]s'. Give one of them another name when importing it (<name> as <alias>).",
	ImportClassConflictOwn:       "The class '%[2]s' of '%[1]s' has the same name as a class this program already has. Give it another name when importing it (<name> as <alias>).",
	ImportFileNotFound:           "File '%s' not found.",
	ImportFileSyntax:             "Syntax error in file '%s'.",
	ImportTargetNotFound:         "Target '%[2]s' not found in '%[1]s'.",
	ImportNativeOnly:             "The module '%s' cannot be used in a browser.",

	VariableTypeMismatch:  "'%[1]s' can only hold '%[2]s', but got '%[3]s'.",
	ArgumentTypeMismatch:  "Argument '%[1]s' must be '%[2]s', but got '%[3]s'.",
	ReturnTypeMismatch:    "Function '%[1]s' must return '%[2]s', but returned '%[3]s'.",
	OperandTypeMismatch:   "Operator '%[1]s' cannot combine '%[2]s' and '%[3]s' (there are no implicit conversions).",
	NullOperand:           "Operator '%s' cannot take a null value.",
	UnknownOperator:       "The operator '%s' is not supported here.",
	CallTooDeep:           "Calls are nested too deeply (more than %d levels).",
	SyntaxUnexpectedToken: "Unexpected '%[3]s' at line %[1]d, column %[2]d.",
	SyntaxUnexpectedEnd:   "Unexpected end of input at line %[1]d.",

	ImportUnsupported:    "Importing files is not supported in the web playground; only standard library modules can be imported.",
	InputTypeUnsupported: "A value of type '%s' cannot be read as input.",
	InputToNumberFailed:  "Cannot convert '%s' to a number.",
	InputToBooleanFailed: "Cannot convert '%s' to true/false.",
}
