package errs

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
)

// ExportedCode is one Code with its wording in every language — the shape
// cmd/errsgen turns into the TypeScript catalog the docs sites' browser
// engines use, so the Go catalogs stay the single source of truth.
type ExportedCode struct {
	Name string // identifier: the Code's text after the "Kind." prefix
	Code Code
	En   string
	Ko   string
	Ja   string
}

// Export lists every declared Code in declaration order.
func Export() []ExportedCode {
	out := make([]ExportedCode, 0, len(allCodes))
	for _, c := range allCodes {
		name := string(c)
		for i := 0; i < len(name); i++ {
			if name[i] == '.' {
				name = name[i+1:]
				break
			}
		}
		out = append(out, ExportedCode{Name: name, Code: c, En: enCatalog[c], Ko: koCatalog[c], Ja: jaCatalog[c]})
	}
	return out
}

func quote(s string) string {
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	_ = enc.Encode(s)
	return strings.TrimSuffix(b.String(), "\n")
}

// TypeScriptCatalog renders every code and catalog as the TypeScript module
// (errCatalog.ts) the docs sites' browser engines import.
func TypeScriptCatalog() string {
	codes := Export()
	var b strings.Builder
	b.WriteString("// Code generated by `go run ./cmd/errsgen` from hana/errs — DO NOT EDIT.\n")
	b.WriteString("// Edit the Go catalogs (errs/ko.go, ja.go, en.go) and regenerate.\n\n")
	b.WriteString("export const Codes = {\n")
	for _, c := range codes {
		fmt.Fprintf(&b, "  %s: %s,\n", c.Name, quote(string(c.Code)))
	}
	b.WriteString("} as const;\n\n")
	b.WriteString("export type Code = (typeof Codes)[keyof typeof Codes];\n\n")
	b.WriteString("export type Catalog = Record<Code, string>;\n\n")
	b.WriteString("export const catalogs: Record<\"en\" | \"ko\" | \"ja\", Catalog> = {\n")
	for _, lang := range []string{"en", "ko", "ja"} {
		fmt.Fprintf(&b, "  %s: {\n", lang)
		for _, c := range codes {
			text := c.En
			switch lang {
			case "ko":
				text = c.Ko
			case "ja":
				text = c.Ja
			}
			fmt.Fprintf(&b, "    [Codes.%s]: %s,\n", c.Name, quote(text))
		}
		b.WriteString("  },\n")
	}
	b.WriteString("};\n")
	return b.String()
}
