package errs

// jaCatalog is 카나데(Kanade)'s wording. Tone rule: です・ます調 — every
// sentence ends in ~です/~ます/~ません/~ました (errs_test.go lints this).
// Where the docs already quote a message (アクセス違反, リスト範囲超過, 辞書キー
// なし, 定数の再代入), the wording here is the docs' own, verbatim.
var jaCatalog = Catalog{
	ThisNotBound:         "メソッドの外では『私』は使えません。",
	SuperOutsideMethod:   "『親』はクラスのメソッドの中でのみ使えます。",
	StaticOutsideMethod:  "『私たち』はクラスのメソッドの中でのみ使えます。",
	VariableNotFound:     "変数『%s』が見つかりません。",
	InstantiateInterface: "『%s』はインターフェースなので、インスタンスを作れません。",
	InstantiateAbstract:  "『%s』は抽象クラスなので、インスタンスを作れません。",
	StringIndexAssign:    "文字列は変更できない値なので、何番目かの文字を代入し直せません。",
	NativeArgString:      "%d番目の引数は文字列でなければなりません。",
	NativeArgNumber:      "%d番目の引数は数字でなければなりません。",
	NativeArgInteger:     "%d番目の引数は整数でなければなりません。",
	NativeArgList:        "%d番目の引数はリストでなければなりません。",
	NativeArgDict:        "%d番目の引数は辞書でなければなりません。",
	NativeDictStrings:    "%d番目の引数は文字列だけの辞書でなければなりません。",
	ArgCountRange:        "引数は%d個から%d個の間でなければなりません。",
	JSONInvalid:          "JSONの形式が正しくないため、読み取れません。",
	JSONUnsupported:      "JSONに変換できない値が含まれています。",
	CSVInvalid:           "CSVの形式が正しくないため、読み取れません。",
	CSVUnsupported:       "CSVに変換できない値です。行はリスト、セルは文字列か数字である必要があります。",
	CSVDelimiter:         "区切り文字は1文字で、引用符や改行は使えません。",
	RegexInvalid:         "『%s』は正しい正規表現ではありません。",
	RandomRange:          "範囲が正しくありません。最小値%dが最大値%dより大きいです。",
	RandomEmpty:          "空のリストからは選べません。",
	DateInvalid:          "『%s』は指定した書式に合う日付ではありません。",
	NativeListNumbers:    "%d番目の引数は数字だけのリストでなければなりません。",
	NativeListStrings:    "%d番目の引数は文字列だけのリストでなければなりません。",
	ListNotSortable:      "数字同士、または文字列同士のリストだけ並べ替えられます。",
	CallbackNotBoolean:   "条件を決める関数は真か偽を返す必要があります。",
	ConditionNotBoolean:  "%sの値は条件に使えません。条件には真か偽が必要です。",
	ListValueUnsupported: "数字、文字列、真偽値、空っぽだけを扱えます。",
	MathDomain:           "この値では計算できません。",
	StatsNotEnough:       "計算するには値が足りません。",
	RangeStepZero:        "間隔は0にできません。",
	ResultTooLarge:       "結果が大きくなりすぎて作れません。",
	TextEmptyPart:        "探す文字列は空にできません。",
	PadFillLength:        "埋める文字はちょうど1文字でなければなりません。",
	Base64Invalid:        "正しいbase64の文字列ではないため、読み取れません。",
	URLDecodeInvalid:     "正しいURLエンコードではないため、読み取れません。",
	SleepRange:           "待つ時間は0秒以上3600秒以下でなければなりません。",
	FileNotFound:         "『%s』というファイルまたはフォルダが見つかりません。",
	FileIsDirectory:      "『%s』はファイルではなくフォルダです。",
	FileAccessDenied:     "『%s』にアクセスする権限がありません。",
	FileFailed:           "『%s』のファイル操作を完了できません。",
	FileBlocked:          "この実行ではファイルアクセスが無効になっています。",
	NetBlocked:           "この実行ではネットワークアクセスが無効になっています。",
	SocketBadHandle:      "ソケット%s番は存在しないか、すでに閉じられています。",
	SocketNotConnection:  "待ち受け中のソケットでは送受信できません。",
	SocketNotListener:    "接続済みのソケットでは新しい接続を受け入れられません。",
	SocketConnectFailed:  "『%s』に接続できません。",
	SocketListenFailed:   "『%s』で接続を待ち受けられません。",
	SocketTimeout:        "決めた時間を過ぎました。",
	SocketFailed:         "ソケットの操作を完了できません。",
	SocketPort:           "ポートは0以上65535以下の整数である必要があります。",
	HTTPBadURL:           "『%s』はhttpまたはhttpsのアドレスではありません。",
	HTTPFailed:           "『%s』へリクエストを送れません。",
	HTTPTooLarge:         "『%s』から受け取った内容が大きすぎて、すべて読めません。",
	HTTPBadMethod:        "『%s』は使えないリクエスト方式です。",
	ClassNotFound:        "クラス『%s』が見つかりません。",

	GlobalFunctionNotFound: "関数『%s』が見つかりません。",
	StaticMethodNotFound:   "静的メソッド『%s』が見つかりません。",
	MethodNotFound:         "メソッド『%s』が見つかりません。",

	NotCallable:             "呼び出せない値です。",
	NotAList:                "リストではありません。",
	NotIterable:             "繰り返せない値です。",
	RangeMustBeNumbers:      "範囲は数字で指定する必要があります。",
	ListIndexMustBeNumber:   "リストの位置（インデックス）は数字である必要があります。",
	SuperMemberMustBeMethod: "親の属性はメソッドとしてのみ呼び出せます。",
	MethodArgMustBeNumber:   "『%s』の引数は数字である必要があります。",
	MethodArgMustBeString:   "『%s』の引数は文字列である必要があります。",
	NotANumber:              "数字ではありません。",
	InvalidOperands:         "この演算はこれらの値には使えません。",
	ListOnlyMethod:          "リストにのみ使えるメソッドです。",

	MemberAccessOnString:    "文字列にはこのようにメンバーとしてアクセスできません。",
	MemberAccessUnsupported: "『%s』型の値にはメンバーとしてアクセスできません。",

	ListEmpty:             "リストが空です。",
	ListIndexOutOfRange:   "リストの長さを超えた位置（インデックス）です。",
	StringIndexOutOfRange: "文字列の長さを超えた位置です。",

	DictKeyNotFound:      "辞書から '%v' という名前を見つけることができません。",
	StaticMemberNotFound: "静的メンバー『%v』が見つかりません。",

	ArgCountExact:    "引数が%d個必要です。",
	TooManyArguments: "引数が多すぎます。%d個が必要ですが、%d個渡されました。",
	MissingArgument:  "引数『%s』が必要です。",

	ConstantAssignment: "定数 '%s' の値は変更できません。",

	PrivateMethodAccess:   "'%s' 機能は内部専用(private)なので外部から呼ぶことはできません。",
	PrivateFieldAccess:    "'%s' 属性は内部専用(private)なので外部から呼ぶことはできません。",
	ProtectedMethodAccess: "'%s' 機能は継承されたクラス専用(protected)なので外部から呼ぶことはできません。",
	ProtectedFieldAccess:  "'%s' 属性は継承されたクラス専用(protected)なので外部から呼ぶことはできません。",

	InterfaceNotImplemented: "クラス '%s' はインターフェース '%s' の '%s' メソッドを実装しなければなりません。",

	DivideByZero: "0で割ることはできません。",

	ConvertToNumberFailed:     "『%s』を数字に変換できません。",
	ConvertToNumberInvalid:    "数字に変換できない値です。",
	ConvertToCodeNeedsOneChar: "<%s>には長さ1の文字列が必要です。",
	ConvertToTextNeedsNumber:  "数字以外の値は文字に変換できません。",

	ImportNativeFunctionNotFound: "DLLパッケージ『%s』にネイティブ関数『%s』が見つかりません。",
	ImportDLLNotFound:            "パッケージ『%s』のDLLが見つかりません。",
	ImportManifestInvalid:        "パッケージ設定ファイルに問題（%[2]s）があるため、パッケージ『%[1]s』を使えません。",
	ImportNativeMissing:          "パッケージ『%s』には%s用のネイティブファイルがありません。",
	ImportNativeLoadFailed:       "ネイティブファイル『%s』を読み込めません。",
	NativeCallFailed:             "『%[2]s』という理由で、ネイティブ関数『%[1]s』が失敗しました。",
	ImportPluginUnsupported:      "%sではネイティブプラグインを利用できません。",
	ImportUnsupportedLocale:      "パッケージ『%[1]s』には『%[2]s』用のエントリがないため、持ってこられません。",
	ImportPackageSyntax:          "パッケージ『%s』のファイル『%s』に文法エラーがあります。",
	ImportPackageNotFound:        "パッケージ『[%s]』が見つかりません。",
	ImportPackageNotInstalled:    "パッケージ『[%s]』がインストールされていません。「hana install」でダウンロードできます。",
	ImportClassConflict:          "『%[1]s』のクラス『%[2]s』と同じ名前のクラスが、『%[3]s』にもあります。持ってくるときに〈名前〉を〈別名〉に持ってこようで、片方に別の名前を付ける必要があります。",
	ImportClassConflictOwn:       "『%[1]s』のクラス『%[2]s』と同じ名前のクラスを、このプログラムがすでに持っています。持ってくるときに〈名前〉を〈別名〉に持ってこようで、別の名前を付ける必要があります。",
	ImportFileNotFound:           "ファイル『%s』が見つかりません。",
	ImportFileSyntax:             "ファイル『%s』に文法エラーがあります。",
	ImportTargetNotFound:         "『%s』に『%s』が見つかりません。",
	ImportNativeOnly:             "『%s』モジュールはブラウザでは使えません。",

	VariableTypeMismatch:  "『%[1]s』には『%[2]s』型の値しか入れられません。『%[3]s』の値が渡されました。",
	ArgumentTypeMismatch:  "引数『%[1]s』には『%[2]s』型の値しか渡せません。『%[3]s』の値が渡されました。",
	ReturnTypeMismatch:    "関数『%[1]s』は『%[2]s』型を返す必要がありますが、『%[3]s』の値を返しました。",
	OperandTypeMismatch:   "『%[1]s』演算は『%[2]s』と『%[3]s』の間ではできません。自動変換はしません。",
	NullOperand:           "『%s』演算には空っぽの値を使えません。",
	UnknownOperator:       "『%s』はここでは使えない演算子です。",
	CallTooDeep:           "呼び出しが深く重なりすぎて、%d階層を超えました。",
	IllegalBreak:          "「繰り返しを終わろう」は繰り返しの中でしか使えません。",
	SyntaxUnexpectedToken: "%[1]d行目、%[2]d文字目の「%[3]s」を解釈できません。",
	SyntaxUnexpectedEnd:   "%[1]d行目で文が途中で終わっています。",

	ImportUnsupported:    "Webプレイグラウンドではファイルのインポートに対応していません。標準ライブラリのみインポートできます。",
	InputTypeUnsupported: "『%s』型は入力として受け取れません。",
	InputToNumberFailed:  "『%s』を数字に変換できません。",
	InputToBooleanFailed: "『%s』を真/偽に変換できません。",
}
