package errs

// koCatalog is 하자(Haja)'s wording. Tone rule: 해요체 — every sentence ends
// in ~요 (~해요/~예요/~어요), never ~합니다/~습니다 (errs_test.go lints this).
// Where the docs already quote a message (접근 위반, 목록 범위 초과, 사전 키 없음,
// 상수 재대입), the wording here is the docs' own, verbatim.
var koCatalog = Catalog{
	ThisNotBound:         "메서드 밖에서는 '나'를 쓸 수 없어요.",
	SuperOutsideMethod:   "'부모'는 클래스의 메서드 안에서만 쓸 수 있어요.",
	StaticOutsideMethod:  "'우리'는 클래스의 메서드 안에서만 쓸 수 있어요.",
	VariableNotFound:     "'%s' 변수를 찾을 수 없어요.",
	InstantiateInterface: "'%s'은(는) 인터페이스라서 새로 만들 수 없어요.",
	InstantiateAbstract:  "'%s'은(는) 추상 클래스라서 새로 만들 수 없어요.",
	StringIndexAssign:    "문자열은 바꿀 수 없는 값이라서 몇 번째 글자를 다시 정할 수 없어요.",
	NativeArgString:      "%d번째 인자는 문자열이어야 해요.",
	NativeArgNumber:      "%d번째 인자는 숫자여야 해요.",
	NativeArgInteger:     "%d번째 인자는 정수여야 해요.",
	NativeArgList:        "%d번째 인자는 목록이어야 해요.",
	NativeArgDict:        "%d번째 인자는 사전이어야 해요.",
	NativeDictStrings:    "%d번째 인자는 글자만 든 사전이어야 해요.",
	ArgCountRange:        "인자는 %d개에서 %d개 사이여야 해요.",
	JSONInvalid:          "JSON 형식이 올바르지 않아서 읽을 수 없어요.",
	JSONUnsupported:      "JSON으로 바꿀 수 없는 값이 들어 있어요.",
	CSVInvalid:           "CSV 형식이 올바르지 않아서 읽을 수 없어요.",
	CSVUnsupported:       "CSV로 바꿀 수 없는 값이에요. 행은 목록이고, 칸은 글자나 숫자여야 해요.",
	CSVDelimiter:         "구분자는 글자 하나여야 하고, 따옴표나 줄바꿈은 쓸 수 없어요.",
	RegexInvalid:         "'%s'은(는) 올바른 정규식이 아니에요.",
	RandomRange:          "범위가 잘못됐어요. 최솟값 %d이(가) 최댓값 %d보다 커요.",
	RandomEmpty:          "비어 있는 목록에서는 고를 수 없어요.",
	DateInvalid:          "'%s'은(는) 지정한 서식에 맞는 날짜가 아니에요.",
	NativeListNumbers:    "%d번째 인자는 숫자만 든 목록이어야 해요.",
	NativeListStrings:    "%d번째 인자는 문자열만 든 목록이어야 해요.",
	ListNotSortable:      "숫자끼리 또는 문자열끼리만 정렬할 수 있어요.",
	CallbackNotBoolean:   "조건을 정하는 함수는 참이나 거짓을 돌려줘야 해요.",
	ConditionNotBoolean:  "%s 값은 조건으로 쓸 수 없어요. 조건에는 참이나 거짓이 와야 해요.",
	ListValueUnsupported: "숫자, 문자열, 논리값, 비어있음만 다룰 수 있어요.",
	MathDomain:           "이 값으로는 계산할 수 없어요.",
	StatsNotEnough:       "계산하기에 값이 부족해요.",
	RangeStepZero:        "간격은 0일 수 없어요.",
	ResultTooLarge:       "결과가 너무 커져서 만들 수 없어요.",
	TextEmptyPart:        "찾을 글자는 비어 있을 수 없어요.",
	PadFillLength:        "채울 글자는 딱 한 글자여야 해요.",
	Base64Invalid:        "올바른 base64 글자가 아니어서 읽을 수 없어요.",
	URLDecodeInvalid:     "올바른 URL 인코딩이 아니어서 읽을 수 없어요.",
	SleepRange:           "기다리는 시간은 0초 이상 3600초 이하여야 해요.",
	FileNotFound:         "'%s' 파일이나 폴더를 찾을 수 없어요.",
	FileIsDirectory:      "'%s'은(는) 파일이 아니라 폴더예요.",
	FileAccessDenied:     "'%s'에 접근할 권한이 없어요.",
	FileFailed:           "'%s'에 대한 파일 작업을 마치지 못했어요.",
	FileBlocked:          "이 실행에서는 파일 접근이 꺼져 있어요.",
	NetBlocked:           "이 실행에서는 네트워크 접근이 꺼져 있어요.",
	SocketBadHandle:      "%s번 소켓은 없거나 이미 닫혔어요.",
	SocketNotConnection:  "듣고 있는 소켓으로는 보내거나 받을 수 없어요.",
	SocketNotListener:    "연결된 소켓으로는 새 연결을 받아들일 수 없어요.",
	SocketConnectFailed:  "'%s'에 연결하지 못했어요.",
	SocketListenFailed:   "'%s'에서 연결을 기다리지 못했어요.",
	SocketTimeout:        "정해 둔 시간 안에 끝내지 못했어요.",
	SocketFailed:         "소켓 작업을 마치지 못했어요.",
	SocketPort:           "포트는 0 이상 65535 이하의 정수여야 해요.",
	HTTPBadURL:           "'%s'은(는) http나 https 주소가 아니에요.",
	HTTPFailed:           "'%s'로 요청을 보내지 못했어요.",
	HTTPTooLarge:         "'%s'에서 받은 내용이 너무 커서 다 읽지 못했어요.",
	HTTPBadMethod:        "'%s'은(는) 쓸 수 없는 요청 방식이에요.",
	ClassNotFound:        "'%s' 클래스를 찾을 수 없어요.",

	GlobalFunctionNotFound: "'%s' 함수를 찾을 수 없어요.",
	StaticMethodNotFound:   "'%s' 정적 메서드를 찾을 수 없어요.",
	MethodNotFound:         "'%s' 메서드를 찾을 수 없어요.",

	NotCallable:             "호출할 수 없는 값이에요.",
	NotAList:                "목록이 아니에요.",
	NotIterable:             "반복할 수 없는 값이에요.",
	RangeMustBeNumbers:      "범위는 숫자로 정해야 해요.",
	ListIndexMustBeNumber:   "목록의 위치(인덱스)는 숫자여야 해요.",
	SuperMemberMustBeMethod: "부모의 속성은 함수(메서드)로만 부를 수 있어요.",
	MethodArgMustBeNumber:   "'%s'의 인자는 숫자여야 해요.",
	MethodArgMustBeString:   "'%s'의 인자는 문자열이어야 해요.",
	NotANumber:              "숫자가 아니에요.",
	InvalidOperands:         "이 연산은 이 값들에는 쓸 수 없어요.",
	ListOnlyMethod:          "목록에만 쓸 수 있는 메서드예요.",

	MemberAccessOnString:    "문자열에는 이렇게 멤버로 접근할 수 없어요.",
	MemberAccessUnsupported: "'%s' 타입의 값에는 멤버로 접근할 수 없어요.",

	ListEmpty:             "목록이 비어 있어요.",
	ListIndexOutOfRange:   "목록의 길이를 벗어난 위치(인덱스)예요.",
	StringIndexOutOfRange: "문자열의 길이를 벗어난 위치예요.",

	DictKeyNotFound:      "사전에서 '%v' 이름을 찾을 수 없어요.",
	StaticMemberNotFound: "'%v' 정적 멤버를 찾을 수 없어요.",

	ArgCountExact:    "인자가 %d개 필요해요.",
	TooManyArguments: "인자가 너무 많아요. %d개를 기대했는데 %d개를 받았어요.",
	MissingArgument:  "'%s' 인자가 필요해요.",

	ConstantAssignment: "상수 '%s'의 값은 변경할 수 없어요.",

	PrivateMethodAccess:   "'%s' 기능은 내부 전용(private)이라 외부에서 부를 수 없어요.",
	PrivateFieldAccess:    "'%s' 속성은 내부 전용(private)이라 외부에서 부를 수 없어요.",
	ProtectedMethodAccess: "'%s' 기능은 상속된 클래스 전용(protected)이라 외부에서 부를 수 없어요.",
	ProtectedFieldAccess:  "'%s' 속성은 상속된 클래스 전용(protected)이라 외부에서 부를 수 없어요.",

	InterfaceNotImplemented: "클래스 '%s'은(는) 인터페이스 '%s'의 '%s' 메서드를 구현해야 해요.",

	DivideByZero: "0으로 나눌 수 없어요.",

	ConvertToNumberFailed:     "'%s'을(를) 숫자로 바꿀 수 없어요.",
	ConvertToNumberInvalid:    "숫자로 바꿀 수 없는 값이에요.",
	ConvertToCodeNeedsOneChar: "<%s>는 길이가 1인 문자열이 필요해요.",
	ConvertToTextNeedsNumber:  "숫자가 아닌 값은 글자로 바꿀 수 없어요.",

	ImportNativeFunctionNotFound: "DLL 패키지 '%s'에서 네이티브 함수 '%s'를 찾을 수 없어요.",
	ImportDLLNotFound:            "패키지 '%s'의 DLL을 찾을 수 없어요.",
	ImportManifestInvalid:        "패키지 설정 파일에 문제(%[2]s)가 있어서 패키지 '%[1]s'를 쓸 수 없어요.",
	ImportNativeMissing:          "패키지 '%s'에는 %s용 네이티브 파일이 없어요.",
	ImportNativeLoadFailed:       "네이티브 파일 '%s'을(를) 불러올 수 없어요.",
	NativeCallFailed:             "'%[2]s' 때문에 네이티브 함수 '%[1]s'이(가) 실패했어요.",
	ImportPluginUnsupported:      "%s에서는 네이티브 플러그인을 쓸 수 없어요.",
	ImportUnsupportedLocale:      "패키지 '%[1]s'에는 '%[2]s'용 진입점이 없어서 가져올 수 없어요.",
	ImportPackageSyntax:          "패키지 '%s'의 '%s' 파일에 문법 오류가 있어요.",
	ImportPackageNotFound:        "패키지 '[%s]'를 찾을 수 없어요.",
	ImportFileNotFound:           "'%s' 파일을 찾을 수 없어요.",
	ImportFileSyntax:             "'%s' 파일에 문법 오류가 있어요.",
	ImportTargetNotFound:         "'%s'에서 '%s'을(를) 찾을 수 없어요.",
	ImportNativeOnly:             "'%s' 모듈은 브라우저에서 사용할 수 없어요.",

	VariableTypeMismatch:  "'%[1]s'에는 '%[2]s' 타입만 담을 수 있어요. '%[3]s' 값이 들어왔어요.",
	ArgumentTypeMismatch:  "'%[1]s' 인자에는 '%[2]s' 타입만 넘길 수 있어요. '%[3]s' 값이 들어왔어요.",
	ReturnTypeMismatch:    "'%[1]s' 함수는 '%[2]s' 타입을 돌려줘야 하는데 '%[3]s' 값을 돌려줬어요.",
	OperandTypeMismatch:   "'%[1]s' 연산은 '%[2]s'와(과) '%[3]s' 사이에서 할 수 없어요. 자동 형변환은 하지 않아요.",
	NullOperand:           "'%s' 연산에는 비어있음 값을 쓸 수 없어요.",
	UnknownOperator:       "'%s'은(는) 여기서 쓸 수 없는 연산자예요.",
	CallTooDeep:           "호출이 너무 깊게 쌓여서 %d단계를 넘었어요.",
	SyntaxUnexpectedToken: "%[1]d번째 줄 %[2]d번째 글자의 '%[3]s'를 이해할 수 없어요.",
	SyntaxUnexpectedEnd:   "%[1]d번째 줄에서 문장이 끝나지 않았어요.",

	ImportUnsupported:    "웹 놀이터에서는 파일 가져오기를 지원하지 않아요. 표준 라이브러리만 가져올 수 있어요.",
	InputTypeUnsupported: "'%s' 타입은 입력으로 받을 수 없어요.",
	InputToNumberFailed:  "'%s'을(를) 숫자로 바꿀 수 없어요.",
	InputToBooleanFailed: "'%s'을(를) 참/거짓으로 바꿀 수 없어요.",
}
