package lsp

import (
	"encoding/json"
	"fmt"
	"strings"
)

// LanguageKeys lists the languages the browser engines are generated for
// ("hari", "kanade"), matching the ids used by the language tables.
var LanguageKeys = []string{"hari", "kanade"}

func languageByID(id string) *language {
	switch id {
	case "hari":
		return hariLang
	case "kanade":
		return kanadeLang
	}
	return nil
}

func quoteTS(s string) string {
	b, _ := json.Marshal(s)
	return strings.ReplaceAll(string(b), `\u0026`, "&")
}

func tsList(name string, words []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "  %s: [\n", name)
	for _, w := range words {
		fmt.Fprintf(&b, "    %s,\n", quoteTS(w))
	}
	b.WriteString("  ],\n")
	return b.String()
}

// TypeScriptKeywords renders one language's completion words as the module the
// docs sites' browser editors import (lspKeywords.ts), so the browser suggests
// exactly what the language server does. It returns "" for an unknown language.
func TypeScriptKeywords(lang string) string {
	l := languageByID(lang)
	if l == nil {
		return ""
	}
	var b strings.Builder
	b.WriteString("// Code generated by `go run ./cmd/lspgen` from hana/lsp — DO NOT EDIT.\n")
	b.WriteString("// Edit the keyword tables in hana/lsp/language.go and regenerate.\n\n")
	b.WriteString("export const lspKeywords = {\n")
	b.WriteString(tsList("keywords", l.keywords))
	b.WriteString(tsList("comparisons", l.comparisons))
	b.WriteString(tsList("words", l.words))
	b.WriteString("} as const;\n")
	return b.String()
}
