package std

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
)

func quote(s string) string {
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	enc.Encode(s)
	return strings.TrimSuffix(b.String(), "\n")
}

// TypeScriptNames renders the name table for one language as the TypeScript
// module a docs engine imports (stdNames.ts). It carries only that language,
// because each docs repo runs a single language. Modules marked NativeOnly are
// listed with `nativeOnly: true`: the browser engine has no implementation for
// them and refuses their import with a dedicated error.
func TypeScriptNames(lang string) string { return typeScriptNames(lang, Modules) }

func typeScriptNames(lang string, modules []Module) string {
	var b strings.Builder
	b.WriteString("// Code generated by `go run ./cmd/stdgen` from hana/std — DO NOT EDIT.\n")
	b.WriteString("// Edit the name tables in hana/std and regenerate.\n\n")
	b.WriteString("export interface StdModule {\n")
	b.WriteString("  id: string;\n  name: string;\n  nativeOnly?: boolean;\n")
	b.WriteString("  functions: readonly { id: string; name: string }[];\n}\n\n")
	b.WriteString("export const stdModules: readonly StdModule[] = [\n")
	for _, m := range modules {
		fmt.Fprintf(&b, "  {\n    id: %s,\n    name: %s,\n", quote(m.ID), quote(ModuleName(lang, m.ID)))
		if m.NativeOnly {
			b.WriteString("    nativeOnly: true,\n")
		}
		b.WriteString("    functions: [\n")
		for _, f := range m.Functions {
			fmt.Fprintf(&b, "      { id: %s, name: %s },\n", quote(f), quote(FunctionName(lang, f)))
		}
		b.WriteString("    ],\n  },\n")
	}
	b.WriteString("];\n")
	return b.String()
}
